name: pipeline
on:
 push:
   branches:
     - "main"

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/alexraskin/goping:latest
            ghcr.io/alexraskin/goping:${{ github.sha }}

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://swarmctl.alexraskin.com/v1/update/goping?image=ghcr.io/alexraskin/goping:${{ github.sha }}"
          method: "POST"
          timeout: 60000
          customHeaders: '{"Authorization": "Bearer ${{ secrets.AUTH_TOKEN }}"}'